#!/bin/bash

DPDK_VERSION=18.02
DPDK_CARD_IDS=(00:07.0 00:09.0)
DPDK_CARD_NAMES=(ens7 ens9)

LINUX_DRIVER=e1000
LINUX_CARD_IDS=
LINUX_CARD_NAMES=
LINUX_NETMASKS=
LINUX_FIREWALL=
LINUX_ROUTE_NETWORKS=
LINUX_ROUTE_VIA=
